### ISSUE TITLE
search

### ISSUE THREAD

**Issue by retorquere** [retorquere/zotero-erdos#2]
now with search interface, open with `Tools` -> `Erdos path`.

**Comment by retorquere** [comment]
@Jack-613 please try this build

**Comment by Jack-613** [comment]
Perfect Emile,  great :-)

Thank you so much !

Best Jakob

**Comment by retorquere** [comment]
Have you tried clicking the results? It will select the corresponding item in Zotero.

**Comment by retorquere** [comment]
Can I release this?

**Comment by Jack-613** [comment]
Yes, I tried clicking the results => jumping to corresponding Item :-) very good, also the layout !

Please release this.

THX !!

**Comment by retorquere** [comment]
Strings etc can still be changed. The major work for this was finding the mostly deprecated documentation, and finding out what still works of what is documented.

I'll put out a release when I'm back at my desk.

**Comment by retorquere** [comment]
released
